[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BroadcastableStructs = "69bbf4a4-23d0-4da4-b4ea-97dbcb735a40"
ChainCutters = "b0ce31d9-63c8-4e5e-905b-7866bc977c93"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
Zygote = "0.3"
ZygoteRules = "0.1"
julia = "1"
